language: scala
cache:
  directories:
  - .sbt
node_js:
  - "0.8"
  - "0.10"
scala:
  - 2.10.5
jdk:
  - oraclejdk7
  - oraclejdk8
before_install:
  - npm install grunt -g --save-dev
install: 
  - npm install
before_script: 
  - grunt build:dev
script:
  - sbt compile
  - sbt stage
  - sbt test
branches:
  -master
notifications:
  email:
    - mrparovoz@gmail.com
