language: scala
cache:
  directories:
  - .sbt
node_js:
  - "0.8"
  - "0.10"
before_script:
  - npm install grunt --save-dev
script:
  - sbt compile
  - sbt test
branches:
  -master
scala:
  - 2.10.5
jdk:
  - oraclejdk7
  - openjdk7

notifications:
  email:
    - mrparovoz@gmail.com
  
