language: scala
cache:
  directories:
  - .sbt
before_script:
  - npm install grunt-cli -g
script:
  - sbt compile
  - grunt build:dev
  - sbt test
branches:
  -master
scala:
  - 2.10.5
jdk:
  - oraclejdk7
  - openjdk7

notifications:
  email:
    - mrparovoz@gmail.com
  
